language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - travis_retry composer self-update
  - phpenv config-add travis.config.ini

install: composer install --dev

script: ./vendor/bin/phpunit
