language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: PHPCS=true
    - php: 7.0
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.config.ini; fi;'

install: composer install --dev

script:
  - ./vendor/bin/phpunit
  - if [[ "$PHPCS" == "true" ]]; then ./vendor/bin/php-cs-fixer fix ./src --no-interaction --dry-run --diff; fi
  - if [[ "$PHPCS" == "true" ]]; then ./vendor/bin/php-cs-fixer fix ./tests --no-interaction --dry-run --diff; fi
