language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: PHPCS=true
    - php: 7.0
    - php: hhvm-3.9
      sudo: true
      dist: trusty
      group: edge
  allow_failures:
    - php: 7.0
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.php-cs-fixer"

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - travis_retry composer self-update
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then phpenv config-add travis.config.ini; fi;'

install: composer install --dev

script:
  - ./vendor/bin/phpunit
  - if [[ "$PHPCS" == "true" ]]; then ./vendor/bin/php-cs-fixer fix ./src --no-interaction --dry-run --diff --cache-file "$HOME/.php-cs-fixer/.php_cs.cache"; fi
  - if [[ "$PHPCS" == "true" ]]; then ./vendor/bin/php-cs-fixer fix ./tests --no-interaction --dry-run --diff --cache-file "$HOME/.php-cs-fixer/.php_cs.cache"; fi
